import { StyleSheet } from "react-native";
import fonts from "../../../../../assets/fonts";
import { fontSizes, itemSizes, spacing } from "../../../../common/variables";
import colors from "../../../../theme/colors";

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.backgroundColor,
        paddingHorizontal:spacing.medium
    },
    inputView:{
        backgroundColor:"white",
        flexDirection:"row",
        alignItems:"center",
        padding:spacing.medium,
        borderRadius:spacing.small
    },
    textInput:{
        paddingHorizontal:spacing.medium,
        color:"#333",
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraSmall,
        flex:1,
    },
    search:{
        width:itemSizes.item20,
        height:itemSizes.item20,
        tintColor:"grey"
    },
    logout:{
        width:itemSizes.item20,
        height:itemSizes.item20,
        tintColor:"#333"
    },
    logoutText:{
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraExtraSmall,
        color:"#333",
        marginRight:spacing.small
    },
    logContainer:{
        flexDirection:'row',
        position:'absolute',
        right:0
       // alignItems:"center"
    },
    titleView:{
        width:"100%",
        //  paddingHorizontal:spacing.medium,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        marginBottom:spacing.medium,
       
    },
    mainView:{
       backgroundColor:"white",
       marginTop:spacing.large,
       borderRadius:spacing.small,
       padding:spacing.mediumLarge
    },
    uniqText:{
        fontFamily:fonts.bold,
        fontSize:fontSizes.small,
        color:"#333",
    },
    bold:{
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraSmall,
        color:"#333",
        textAlign:"left"
    },
    subText:{
        fontFamily:fonts.regular,
        fontSize:fontSizes.extraExtraSmall,
        color:"#333",
        textAlign:"left",
        marginTop:spacing.small
    },
    ratingView:{
        flexDirection:"row",
        alignItems:"center",
        marginTop:spacing.small
    },
    ratingText:{
        color:colors.appSecondary,
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraSmall,
        marginLeft:spacing.small
    },
    totalRatingText:{
        color:"grey",
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraSmall,
    },
    ratingStar:{
        width:itemSizes.item15,
        height:itemSizes.item15,
        tintColor:colors.appSecondary
    },
    star:{
        width:itemSizes.item35,
        height:itemSizes.item35,
        tintColor:colors.appSecondary
    },
    giveRatingView:{
        flexDirection:"row",
        justifyContent:"space-between",
        width:"100%",
    },
    encolseView:{
        backgroundColor:colors.backgroundColor,
        padding:spacing.small,
        borderRadius:spacing.small,
        marginTop:spacing.extraExtraLarge,
    },
    howWould:{
        color:"#333",
        fontFamily:fonts.semiBold,
        fontSize:fontSizes.extraExtraSmall,
        marginVertical:spacing.small
    }
})